name: background_fetch
description: Periodic callbacks in the background for both iOS and Android.  Includes Android Headless implementation.
version: 1.3.8
homepage: https://github.com/transistorsoft/flutter_background_fetch

environment:
  sdk: ^3.6.0
  flutter: ">=3.13.0"
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: BackgroundFetchPlugin
topics:
  - background-task
  - background
